### PR TITLE
Change comment color to red

### PR DESCRIPTION
**Pull request by WTFox**
This changes the comment color to from green to red. Green implies success, whereas red stands out.

There's no related issue (I can create one, if needed).

image

### CODE REVIEW

**Comment by matryer** [comment]
I could live with this @WTFox, thank you - Would you also be able to update the image in the README?

**Comment by WTFox** [comment]
> Would you also be able to update the image in the README?

Oops, good catch. Done!

**Comment by WTFox** [comment]
This looks like to be a pretty safe merge as is. Just checking in to see if there's anything I'm missing. Thanks!

**Comment by matryer** [comment]
Sorry this one slipped through the net.

**Comment by WTFox** [comment]
No problem! Thanks for the merge

**Pull request merged**
