### PR TITLE
Leave flag.Parse() for go test

### LINKED ISSUE #17: flag.Parse in init() prevents own flags in tests
With the commit https://github.com/matryer/is/commit/46663c17c43e9963aa1aae09e7bbdbb35d7b9dda the parsing of the flags has changed to the use of `flag.Parse()`.
Because `flag.Parse()` is called in [`init()`](https://github.com/matryer/is/blob/master/is.go#L78),  it prevents the source package (the one, that uses `github.com/matryer/is`) from defining and using it's own flags, because the calls to e.g. `flag.Bool(...)` will be after the execution of `flag.Parse()` and therefore these flags are not considered and the execution of `go test` fails with `flag provided but not defined: ...`.

This leaves us with two options:

1. Revert the above mentioned commit
2. Under the assumption, that this package is mainly (only) used for testing with `go test`, then it would also be save to remove the call to `flag.Parse()` in `init()`, because `go test` will execute `flag.Parse()`

### PR DESCRIPTION
**Pull request by breml**
Fixes #17

### CODE REVIEW

**Comment by breml** [comment]
@matryer can you please have a look at this PR, it just bite my again and I would really appreciate, if this could be fixed.

**Comment by breml** [comment]
@matryer Could you please have a look at this PR, because this bug is pretty annoying for us.

**Comment by breml** [comment]
@matryer under the assumption, that this library is only ever used for tests (read: in combination with `go test`), then there is no functional change, because `go test` does call `flag.Parse()`. 
Because in order to use this library one needs a `*testing.T`, I think it is pretty save to assume, that this library is only used with tests.

**Comment by matryer** [comment]
Great, thanks.

**Comment by breml** [comment]
@matryer Thank you very much. Could you please tag a new release such that we can reference it with `dep`?

**Pull request merged**
