### PR TITLE
Support NO_COLOR (https://no-color.org).

### PR DESCRIPTION
**Pull request by AlekSi**
Also, handle `IS_NO_COLOR=1` and `IS_NO_COLOR=FALSE`.

### CODE REVIEW

**Comment by matryer** [comment]
@AlekSi thanks for this - shall we remove mention of `IS_NO_COLOR` (while still supporting it) at the same time?

**Comment by AlekSi** [comment]
I don't know :)

**Comment by matryer** [comment]
@AlekSi let's :) Would you be able to add it to your PR?

**Comment by AlekSi** [comment]
PTAL

**Review by matryer — APPROVED** [review]
LGTM - thank you

**Pull request merged**
